           const bookData = [
                {
                    text: `
                        <h4>Something’s Wrong With The World</h4>
                            <p class="text-black-50 mb-0">People everywhere can sense it—something just isn’t right. Some feel a growing dread, as if something terrible is about to unfold. And then there are the Christians, who keep saying, “Jesus is coming soon.” The Bible lays out a <b>prophetic blueprint explaining our present chaos and the storm still ahead</b>. The Rapture will come without warning—like a thief in the night—leaving the world stunned and reeling. A charismatic figure will rise in the aftermath, offering answers that sound like hope. But every word he speaks will be a deception straight from the pit of hell.</p>
                            <p class="text-black-50 mb-0">This book is a humble attempt to answer the biggest question people will have at that moment: “Where did everyone go?” When millions vanish in an instant, homes will be looted, fear will spread, and the search for truth will begin. Books like this are meant to be found in that hour of desperation—<b>to point to the only truth that matters</b>.</p>
                        
						
							<h4>Don’t Ignore the Turmoil Around You</h4>
							<p class="text-black-50 mb-0">Everything’s changing so fast, and <b>it’s been a brutal, nonstop grind</b>. First, the COVID-19 pandemic, then the riots, and now our world is on the verge of being overthrown from within and without—all while the World Economic Forum is implementing its plan for world domination.</p>
							<p class="text-black-50 mb-0">Has the world gone crazy? <b>The issues we face today are unprecedented</b>: pipeline sabotage, drought, food and water shortages, fuel crises, moral decay, artificial intelligence disruptions, the dollar’s decline, government corruption, concentration camps, geopolitical tensions in Ukraine and Taiwan, child trafficking, abortion, mass shootings, constant surveillance, a boiling crisis in the Middle East, global instability, looming nuclear war, the risk of an electromagnetic pulse (EMP) shutting down everything—the list goes on. Catastrophic natural disasters and increasing satanic influences only add to the chaos.</p>
							<p class="text-black-50 mb-0">Plus, we are now hit with <b>extreme division in our country</b>. Organized chaos is erupting across the nation and the world. Some advocate for violent revolution, <b>disregarding life and liberty</b>. With calls to defund the police, murder rates in cities have doubled and tripled, crime rates are soaring, gangs are multiplying, and cities are burning.</p>
                    `,
                    image: "assets/img/page1.jpg"
                },
                {
                    text: `
                        <p class="text-black-50 mb-0">Lies, deception, cunning, and manipulation characterize today’s society. People watch the so-called “news” and are <b>stirred into a frenzy by what they see</b>. “If it bleeds, it leads,” as the saying goes. Once, journalism focused on answering the fundamental questions: Who, what, when, where, why, and how? Today’s news is just a <b>glorified opinion piece</b>, using cherry-picked footage and twisted words to spin reality into its opposite, fitting neatly into the globalist agenda.</p>
						<p class="text-black-50 mb-0">“If you tell a lie long enough and loud enough, the people will believe it.” While this quote is often attributed to Karl Marx, it more accurately reflects the <b>principles of propaganda</b> used to manipulate the masses. And the people eat up the delicious lies!</p>
                        <p class="text-black-50 mb-0">Technology has paved the way for the Beast System, with Big Data recording everything about you. Where you spend your money, where you go, and everything you communicate electronically is <b>stored for future use</b>. The government is actively pushing for a digital currency, which will eliminate privacy in financial transactions. Eventually, those who do not conform to the state’s dictates will have their accounts shut down. Surveillance cameras are everywhere, tracking your every move. Facial recognition software can identify individuals in a stadium-sized crowd within seconds. Even your web browser’s so-called “private mode” is an illusion—everything is permanently recorded.</p>
                        <p class="text-black-50 mb-0">Then, there is the <b>rising discourse about aliens and UFOs</b>. Recently, the U.S. Navy admitted we are not alone, releasing videos of pilots encountering unidentified aerial phenomena performing maneuvers impossible with human technology. Scientists from the Search for Extra-Terrestrial Intelligence (SETI) report repeating radio frequency bursts across the galaxy, which they suggest might be from intelligent sources. With increasing chatter about alien encounters, governments are being pushed to declassify what they know about these visitations. It won’t be long before world leaders announce: “The aliens are here!”</p>
                        <p class="text-black-50 mb-0">This is the unsettling reality we now face—<b>a reality we can’t ignore</b>. It sets the stage for what’s coming next.</p>
                    `,
                    image: "assets/img/page2.jpg" // Replace with your actual image path
                },
                {
                    text: `
                        <h4>Mystery of the Mass Disappearance</h4>
						<p class="text-black-50 mb-0">Any day now (or perhaps just recently, depending on when you read this), <b>millions of people</b> will mysteriously vanish from the Earth at the peak of global chaos. Imagine you are driving to pick up groceries when an old Toyota suddenly veers out of control, crashing into a school bus that was dropping off children. You see the bus driver frantically looking around, searching for the missing kids. He stumbles into the street, <b>only to be struck by an oncoming car</b>. Then it dawns on you—cars are crashing all around. Within minutes, you see a plane nosedive behind the grocery store, hitting the ground with a deafening explosion, sending fire and debris in every direction. How is this happening, you wonder, your hands shaking uncontrollably?</p>
						<p class="text-black-50 mb-0">You drive home in a panic, weaving frantically through the wreckage. You turn on the radio and hear sheer madness: Entire schools of children—particularly the youngest—are missing and unaccounted for; driverless cars crash into buildings; planes fall out of the sky; trains derail—pandemonium. Loved ones gone without a trace.</p>
						<p class="text-black-50 mb-0">The broadcasters sound shaken, <b>unsure of what they’re reading from the teleprompter</b>. News anchors struggle to stay composed while taking calls from frantic parents and eyewitnesses. Social media is a flood of confusion—live videos, desperate pleas, conspiracy theories, and wild speculation. Sirens scream in every direction as first responders scramble to control the growing chaos.</p>
						<p class="text-black-50 mb-0">You barely make it home, hesitating to catch your breath in the driveway. Once inside, dazed and trying to steady yourself, you turn on the TV. Every channel is <b>flooded with footage of chaos</b>—fires, disasters, and a thousand different catastrophes. The damage will cost billions, and it will take months to restore order. But then, as if the world collectively holds its breath, a chilling realization takes hold: <b>countless people have vanished into thin air</b>.</p>
						<p class="text-black-50 mb-0">Phones ring unanswered, their shrill cries echoing through half-empty homes where someone should be. Hospitals overflow—<b>not just with the injured, but with the terrified</b>. Nurses weep in the halls. Airports choke with bodies and silence, blinking arrival boards no one reads. Some houses are deserted—meals still steaming, bathtubs running, TVs murmuring to no one. Other people remain—shaking, screaming, frozen in doorways, calling out names that won’t answer. And the streets are filled with <b>the awful noise of the left behind</b>—sirens, sobs, and the sound of a world suddenly much too quiet. Something sacred has been torn away, and those still here can feel it in their bones.</p>

                    `,
                    image: "assets/img/page3.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">Videos roll in—two friends walking side by side, and in an instant, one is gone. A nanny cam records a room full of preschoolers napping peacefully until, one by one, their blankets collapse as if <b>an unseen force has plucked them away</b>. The same eerie scenes play on every station, in every language, across every country. And the world asks in unison: “Where did everyone go?” They are met with only silence. Their voices grow louder, more frantic: <b><i>“WHERE DID EVERYONE GO?!”</i></b></p>
						<h4>The Rapture Is Closer Than You Think</h4>
						<p class="text-black-50 mb-0">The Bible frequently predicts and emphasizes this event, which Christians call the Rapture. While the Rapture is part of the broader “Second Coming,” it should not be confused with Christ’s final return to establish His kingdom on Earth. The Rapture will occur first, removing believers from the coming wrath—ushering them into the presence of their Savior. It will be <b>sudden, unexpected, and unmistakable</b>. When the trumpet sounds, the dead in Christ will rise, and those who are alive will be caught up together with them in the clouds. This is our hope—the hope of never dying, of being transformed in an instant, and of <b>being rescued from this sin-sick planet</b> before the Great and Terrible Day of the Lord. It is not fear that drives this hope, but love—a longing to be with the One who promised, “I go to prepare a place for you.”</p>
						<p class="text-black-50 mb-0">This pamphlet is meant to keep biblical truth front and center amid the growing flood of deception that will only intensify as the end of the age approaches. In a world flooded with false narratives and manipulated images, where the media often <b>distorts more than it reveals</b>, discernment is no longer optional—it is essential. The lines between truth and falsehood are blurring rapidly, even within religious circles. Many will be <b>led astray by smooth words</b>, counterfeit miracles, and doctrines that sound right but are rooted in darkness. The Bible warns of a time when people will no longer tolerate sound teaching but will gather teachers who say <b>what their itching ears want to hear</b>. That time is here. And as confusion deepens, believers must anchor themselves to the unchanging Word of God. This is not a time for casual faith. It is a time to <i>wake up, be alert, and walk in the light</i>.</p>
						<p class="text-black-50 mb-0">During the reign of the Antichrist, nothing can be believed, for the rulers of this world will speak in the language of their father, whom Christians call the devil, the father of lies. He will rule for seven years, and the full explanation of his dictatorship and world events is carefully chronicled in the Book of Revelation. It is this period from which we long to be spared. His return for the faithful, also called the Bride of Christ, is very close at hand. So, will you be ready when He comes for His bride?</p>
                    `,
                    image: "assets/img/page4.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						
						<p class="text-black-50 mb-0">“Do not let your hearts be troubled. Believe in God? Believe also in Me. In my Father’s house, there are many rooms. If it were not so, I would have told you. I am going to prepare a place for you. And if I go to prepare a place for you, I will come again and will take you to Myself, that where I am, you may also be.” (John 14:1-3)</p>
						<p class="text-black-50 mb-0">“But we do not want you to be uninformed, brothers, about those who have fallen asleep, that you may not grieve as others who have no hope. Since we believe that Jesus died and rose again, even so, through Jesus, God will bring those who have fallen asleep with Him. For this we declare to you by a word from the Lord, that we who are alive, who are left until the coming of the Lord, will not precede those who have fallen asleep, for the Lord Himself will descend from heaven with a cry of command, the voice of the archangel, and the sound of the trumpet of God. And the dead in Christ will rise first. Then we who are alive, who are left, will be caught up with them in the clouds to meet the Lord in the air, and so we will always be with the Lord. Therefore, encourage one another with these words.” (1 Thessalonians 4:13-18)</p>
						<h5>Tim Lahaye, co-author of the Left Behind series, notes 14 events of the Rapture:</h5>
						<ol>
							<li>The Lord Himself will descend from His Father’s house, where He has prepared a place for us (see John 14:1-3, 1 Thessalonians 4:16).</li>
							<li>He will come again to receive us to Himself (see John 14:1-3).</li>
							<li>He will resurrect those who have fallen asleep in Him, those who are deceased (see 1 Thessalonians 4:14-15).</li>
							<li>The Lord will shout as He descends. This will take place in the “twinkling of an eye” (see 1 Corinthians 15:52).</li>
							<li>We will hear the archangel’s voice and God’s trumpet call (see 1 Thessalonians 4:16).</li>
							<li>The dead in Christ will rise first (see 1 Thessalonians 4:16).</li>
							<li>Then, we who are alive and remain will have our Earthly bodies transformed into our immortal, heavenly bodies (see 1 Corinthians 15:51, 53).</li>
							<li>We will be caught up (Raptured) together (see 1 Thessalonians 4:17).</li>
							<li>We will be caught up in the clouds, where believers from all of history will reunite (see 1 Thessalonians 4:17).</li>
							<li>We will meet the Lord in the air (see 1 Thessalonians 4:17).</li>
							
						</ol>

                    `,
                    image: "assets/img/page5.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						
						<ol start="11">
							<li>Christ will receive us to Himself and take us to the Father’s house, “That where I am, you may be also” (see John 14:3).</li>
							<li>“And so we shall always be with the Lord” (see 1 Thessalonians 4:17).</li>
							<li>At the call of Christ for believers, He will judge all things. Christians will stand before the judgment seat of Christ (see Romans 14:10, 2 Corinthians 5:10).</li>
							<li>This judgment prepares Christians for the Marriage of the Lamb. Before Christ returns to the Earth in power and great glory, He will meet His bride, the church, and the marriage supper will take place. In the meantime, after the church is Raptured, the world will simultaneously suffer the unprecedented outpouring of God’s wrath, which our Lord calls the Great Tribulation (see Matthew 24:21).</li>
						</ol>
						<p class="text-black-50 mb-0">Notice the phrase <i>“caught up”</i> from 1 Thessalonians 4:17, which comes from the Greek word <i>harpazo</i>. Harpazo also means snatch, carry off, lay hold of, snatch away, suddenly take away, and take by force. <b>This will be a sudden event</b>. In 1 Corinthians 15:52, we read a different view of this event: “Listen, I tell you a mystery; we will not all sleep, but we will all be changed—in a flash, in the twinkling of an eye, at the last trumpet. For <b>the trumpet will sound</b>, the dead will be raised imperishable, and we will be changed.” So, in an instant of indivisible time, quicker than the blink of an eye, the faithful of all ages will be transformed, laid hold of, snatched away, carried off, and taken by force to be <b>rescued from the terrible events that are to come</b> upon the whole world (see Revelation 3:10).</p>
						<h4>Unveiling the Timing of End-Time Events</h4>
						<p class="text-black-50 mb-0">Many books have been written on the <b>Book of Daniel’s prophecies</b>—let us continue our study with these three verses. Daniel was an Old Testament prophet who could <b>interpret dreams</b> and <b>see the future</b>. Many know of Daniel and the lion’s den, Shadrach, Meshach, and Abednego, and King Nebuchadnezzar—but Daniel also wrote, by the inspiration of God, the <b>backbone of prophecy</b> about the end of the age and beyond.</p>
						<p class="text-black-50 mb-0">Understanding Daniel helps us comprehend the <b>timing and sequence of end-time events</b>:</b>
						“Seventy ‘sevens’ are decreed for your holy people and your holy city to finish the transgression, put an end to sin, atone for wickedness, bring in everlasting righteousness, seal up vision and prophecy, and anoint the Most Holy Place. Know and understand this: From the time the word goes out to restore and rebuild Jerusalem until the Anointed One, the ruler, comes, there will be seven ‘sevens’ and sixty-two ‘sevens’… After the sixty-two ‘sevens,’ the Anointed One will be put to death and have nothing. </p>
                    `,
                    image: "assets/img/page6.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						
						<p class="text-black-50 mb-0">The people of the ruler to come will destroy the city and the sanctuary. The end will come like a flood: War will continue until the end, and desolations have been decreed. He will confirm a covenant with many for one ‘seven.’ In the middle of the ‘seven,’ he will put an end to sacrifice and offering. And at the temple, he will set up an abomination that causes desolation, until the end that is decreed is poured out on him.” (Daniel 9:24-27)</p>
						<p class="text-black-50 mb-0">From the passage above, the ‘sevens’ refer to periods of seven years each, <b>so seventy ‘sevens’ represent 490 years</b>. The first sixty-nine ‘sevens’ (483 years) began with the decree by King Artaxerxes in 457 B.C. to restore and rebuild Jerusalem. Exactly 483 years later, Jesus was <b>crucified in 27 A.D.</b> at the end of these sixty-nine ‘sevens.’ However, the seventieth ‘seven’ has not yet begun. The seventieth week of Daniel, this final seven-year period will begin when a covenant is confirmed <b>between the Antichrist and Israel</b>. The Antichrist will break this covenant in the middle of the seven years. A third temple will be rebuilt, but halfway through the seven-year period, the Antichrist will set up an image declaring himself to be ‘god.’</p>
						<p class="text-black-50 mb-0">Thus, a gap exists between the sixty-ninth and seventieth ‘sevens.’ This gap is often called the <b>Age of the Gentiles</b>. Jesus came first for the Jews and then for the Gentiles, so we should be grateful that God allowed the Jews to reject Jesus as their Messiah initially. By the end of the seventieth ‘seven,’ Jesus will have <b>Raptured His church</b>, afflicted Israel under the <b>global dictatorship</b> of the Antichrist for seven years, triumphantly returned to Earth with His saints, thrown Lucifer into the abyss for a thousand years, and established His millennial reign on Earth. Israel will again have the full attention of God—though during very troubled times—and will be <b>the centerpiece of God’s focus</b> to bring them to repentance. This is the primary purpose of the Tribulation.</p>
						<p class="text-black-50 mb-0">However, the path will be difficult. The Bible gives a clear warning of a coming period of unimaginable distress:</b>
							“For then there will be great distress, unequaled from the beginning of the world until now—and <b>never to be equaled again</b>.” (Matthew 24:21)</p>
						<h5>The Tribulation has many names:</h5>
						<p class="text-black-50 mb-0"><b>In the Old Testament:</b> “the time of Jacob’s Trouble,” “the Day of Israel’s Calamity,” “the Indignation,” “the Day of Vengeance,” “the Year of Recompense,” “the Day of Wrath,” “the Day of Darkness,” “the Day of Alarm,” among others. <b>In the New Testament:</b> “the Day of the Lord,” “the Wrath of God,” “the Wrath,” “the Great Tribulation,” “the Hour of Judgment,” and many more.</p>
                    `,
                    image: "assets/img/page7.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>God Judges Evil, Rescues the Righteous</h4>
						<p class="text-black-50 mb-0">The world mocks the idea of divine wrath, but <b>God judges perfectly</b> and has already given us more than enough light to turn back. Every suppressed truth, every godless act, every refusal to repent will be <b>brought into the light</b>. Read carefully from Paul’s letter to the Romans and ask yourself: Is there any part of me that still needs to repent?</p>
						<p class="text-black-50 mb-0">“The wrath of God is being revealed from heaven against all the godlessness and wickedness of people, who suppress the truth by their wickedness since what may be known about God is plain to them because God has made it plain to them. For since the creation of the world, God’s invisible qualities—His eternal power and divine nature—have been clearly seen so that people are without excuse.</p>
						<p class="text-black-50 mb-0">For although they knew God, they neither glorified Him as God nor gave thanks to Him, but their thinking became futile, and their foolish hearts were darkened. Although they claimed to be wise, they became fools and exchanged the glory of the immortal God for images made to look like mortal human beings and birds and reptiles.</p>
						<p class="text-black-50 mb-0">Therefore, God gave them over in the sinful desires of their hearts… They exchanged the truth of God for a lie and worshiped and served created things rather than the Creator—who is forever praised. Amen.</p>
						<p class="text-black-50 mb-0">Furthermore, just as they did not think it worthwhile to retain the knowledge of God, God gave them over to a depraved mind so that they do what ought not to be done. They have become filled with every kind of wickedness, evil, greed, and depravity. They are full of envy, murder, strife, deceit, and malice. They are gossips, slanderers, God-haters, insolent, arrogant, and boastful; they invent ways of doing evil; they disobey their parents; they have no understanding, no fidelity, no love, no mercy. Although they know God’s righteous decree that those who do such things deserve death, they not only continue to do these very things but also approve of those who practice them.” (Romans 1:18-32)</p>
						<p class="text-black-50 mb-0">We see that God does not take kindly to our sinful nature. But in Christ, God forgives our sin, even sparing the faithful from the Tribulation to come: “For God <b>did not appoint us to suffer wrath</b> but to receive salvation through our Lord Jesus Christ.” (1 Thessalonians 5:9)</p>
                    `,
                    image: "assets/img/page8.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">The following Bible verse assures the child of God that they will be spared from this wrath, which is about to be poured out fully upon humanity’s wickedness. Additionally, Revelation 3:10 tells us the faithful Church of Philadelphia—a type of church present at the end of the Church Age—will be spared this terrible time of Tribulation: “Since you have kept my command to endure patiently, I will also keep you from the hour of trial that is going to come on the whole world to test the inhabitants of the Earth.” (Revelation 3:10)</p>
						<p class="text-black-50 mb-0">The idea of the faithful being protected from catastrophic worldwide judgment is not unique to the New Testament. We see where the Old Testament says, “The Lord saw how great the wickedness of man had become on the Earth, and that every inclination of the thoughts of the heart was only evil all the time. The Lord regretted that He had made man on the Earth, and His heart was deeply troubled. So, the Lord said, ‘I will wipe from the face of the Earth the human race I have created… for I regret that I have made them.’ But Noah found favor in the eyes of the Lord.” (Genesis 6:5-8)</p>
						<p class="text-black-50 mb-0">For the sake of one righteous man, God chose to spare humanity. Genesis says the Earth was rotten to its core—corrupt, violent, beyond repair. So God told Noah to build an ark: a vessel of mercy to escape the coming judgment. While the world mocked, he built. Calloused hands. Unshakable faith. He warned of rain beneath a flawless sky. They kept laughing. He kept hammering. The ark was God’s provision, and when Noah entered, the Lord Himself shut the door. Jesus said, “I am the door.” (John 10:9) One door then. One door now.</p>
						<p class="text-black-50 mb-0">Not much has changed. The skies will break open again. Today, many still scoff at the return of Christ. They call it a myth. Panic. Delusion. But the flood came—and so will the Son of Man. The ark was real. The judgment of the wicked in the roaring waves was real. And the return of Jesus is real, too. This wait is a pause for repentance before the storm breaks again:</p>
						<p class="text-black-50 mb-0">“Above all, you must understand that in the last days, scoffers will come, scoffing and following their own evil desires. They will say, ‘Where is this coming he promised? Ever since our ancestors died, everything goes on as it has since the beginning of creation.’ By these waters … the world of that time was deluged and destroyed. By the same word, the present heavens and Earth are reserved for fire, being kept for the Day of Judgment and destruction of the ungodly. The Lord is not slow in keeping His promise, as some of you understand slowness. Instead, He is patient with you, not wanting anyone to perish but for everyone to come to repentance. But the day of the Lord will come like a thief. The heavens will disappear with a roar; the elements will be destroyed by fire, and the Earth and everything in it will be laid bare.” (1 Peter 3:3-4, 6-7, 9-10)</p>
                    `,
                    image: "assets/img/page9.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>It’s All About the Wedding!</h4>
						<p class="text-black-50 mb-0">There is just something special about weddings. Nearly everyone loves being invited to a one and being part of the <b>joyous and solemn occasion</b> celebrating the joining of husband and wife in the presence of God. Every wedding has a distinct theme, with carefully coordinated colors woven into the flowers, napkins, and even the cake. Guests arrive—family and friends all gathered together. At some point, everyone is seated and then stands again as the bride makes her grand entrance. There are smiles and occasional tears of joy as she marches down the aisle. Of course, there’s that look from the groom as he sees her adorned beautifully—hair perfect, nails manicured, an elegant dress flowing behind her. Some catch the gleam in his eye as he sees her like this for the first time, realizing that at this moment, a <b>lifetime of memories is just beginning</b>. Then come the pictures of the perfect day with their closest loved ones and friends. Soon, there is feasting, dancing, music, and don’t forget the sentimental toast! Finally, the honeymoon send-off and consummation.</p>
						<p class="text-black-50 mb-0">The wedding imagery is the most prominent of all the analogies the Bible gives us concerning the Rapture. God symbolizes the union of Himself and His chosen people, analogous to the marriage of a groom and his bride. That is why the Church is referred to as the Bride of Christ (see John 3:29, Ephesians 5:22-23, Romans 7:4, 2 Corinthians 11:2, James 4:4). In biblical times, Jewish weddings were beloved but <b>involved a much more elaborate process</b> than weddings today. First came the betrothal, or ketuvah, where a solemn pledge of commitment to marry was made. Part of the betrothal was paying the purchase price given to the bride’s family. This betrothal was a <b>binding contract, equivalent to marriage</b>, but without living together or consummation.</p>
						<p class="text-black-50 mb-0">Next, the bridegroom would depart for his father’s house, where he would build an addition called the bridal chamber. He was expected to prepare thoroughly to care for his wife in married life. His return for her was imminent—<b>anticipated at any moment</b>—but preparations might take a year or more. Meanwhile, the betrothed bride set herself apart, learning homemaking skills and preparing for their new life together. She focused her hope and devotion solely on her husband-to-be, <b>remaining pure and faithful</b>. Thus, both parties eagerly prepared for each other in loving anticipation.</p>
						<p class="text-black-50 mb-0">Finally, there would be a surprise gathering when the bridegroom, with his attendants, would arrive—<b>usually at night</b>—to take his bride away to the wedding ceremony. The newlyweds would enter the marriage chamber, and the groom would later announce the consummation. Then, a seven-day wedding feast would follow, concluding with the bride’s unveiling. At a wedding feast like this, Jesus performed His first miracle, turning water into wine, due to the host’s embarrassment at running out during such a glorious occasion (see John 2).</p>
                    `,
                    image: "assets/img/page10.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">This Jewish wedding tradition directly symbolizes the relationship between Jesus and His Church. A covenant was established when Jesus proclaimed at the first Lord’s Supper: “This cup is the new covenant in my blood; do this, whenever you drink it, in remembrance of Me.” (1 Corinthians 11:25) There was a purchase price: “You were bought with a price. Therefore, honor God with your body.” (1 Corinthians 6:20)</p>
						<p class="text-black-50 mb-0">The Bride of Christ is set apart, not for comfort, but for readiness when He calls:</p>
						<p class="text-black-50 mb-0">“Husbands, love your wives, just as Christ loved the church and gave Himself up for her, to make her holy, cleansing her by the washing with water through the word, and to present her to Himself as a radiant church, without stain or wrinkle or any other blemish, but holy and blameless.” (Ephesians 5:25; also see 1 Corinthians 1:2, 6:11; Hebrews 10:10, 13:12)</p>
						<p class="text-black-50 mb-0">Then the Bridegroom departed for His Father’s house: “After the Lord Jesus had spoken to them, He was taken up into heaven and sat at God’s right hand.” (Mark 16:19)</p>
						<p class="text-black-50 mb-0">We now await the Bridegroom’s return to take His bride to the wedding feast. Note that the Church is expressly protected from God’s wrath (see 1 Thessalonians 5:9, Revelation 3:10). We also recognize several things clearly: signs of imminent judgment are all around us, and signs of imminent Rapture are evident everywhere. Let us consider the “doctrine of imminence.” Imminence literally means “the next expectation.” In other words, nothing else must occur before this event. The Apostle Paul included himself among those awaiting Christ’s imminent return when he wrote: “We who are still alive and are left will be caught up together with them in the clouds to meet the Lord in the air.” (1 Thessalonians 4:17)</p>
						<p class="text-black-50 mb-0">Since the beginning of Christianity, believers have eagerly awaited this event. Believers are taught to expect the Savior from heaven at any moment:</p>
						<p class="text-black-50 mb-0">“Therefore our citizenship is in heaven. And we eagerly await a Savior from there, the Lord Jesus Christ.” (Philippians 3:20)</p>
						<p class="text-black-50 mb-0">“Just as man was destined to die once, and after that to face judgment, so Christ was sacrificed once to take away the sins of many people; and He will appear a second time, not to bear sin, but to bring salvation to those who are waiting for Him.” (Hebrews 9:27-28)</p>
						<p class="text-black-50 mb-0">“We wait then for the blessed hope—the glorious appearing of our great God and Savior, Jesus Christ, who gave Himself for us to redeem us from all wickedness and to purify for Himself a people that are His very own, eager to do what is good.” (Titus 2:13-14)</p>
                    `,
                    image: "assets/img/page11.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">The anticipation that Christ could return at any moment doesn’t lead to panic—it leads to purpose. It awakens a holy urgency in the hearts of His people. We walk in victory, pursue righteousness, and fix our eyes on things above. We don’t live aimlessly, devoid of hope, or drift with the culture. It reminds us that this world is not our home, and that our King is near. His return is not just a future event—it’s a present motivation. It sharpens our faith and purifies our lives. As Scripture says: “Everyone who has this hope in Him purifies himself, just as He is pure.” (1 John 3:3)</p>
						<h4>The Parable of the Ten Virgins</h4>
						<p class="text-black-50 mb-0">“At that time, the kingdom of heaven will be like ten virgins who took their lamps and went out to meet the bridegroom. Five of them were foolish, and five were wise. The foolish ones took their lamps but did not take any oil with them. The wise, however, took oil in jars along with their lamps. The bridegroom was a long time in coming, and they all became drowsy and fell asleep. At midnight, the cry rang out: ‘Here’s the bridegroom! Come out and meet him!’ Then, all the virgins woke up and trimmed their lamps. The foolish ones said to the wise, ‘Give us some of your oil; our lamps are going out.’ ‘No,’ they replied, ‘there may not be enough for both us and you. Instead, go to those who sell oil and buy some for yourselves.’ But while they were going to buy the oil, the bridegroom arrived. The virgins who were ready went in with him to the wedding banquet. And the door was shut. Later, the others also came, saying, ‘Sir! Sir! Open the door for us!’ But he replied, ‘I tell you the truth, I don’t know you.’ Therefore, keep watch because you do not know the day or the hour.” (Matthew 25:1-13)</p>
						<p class="text-black-50 mb-0">This passage is both exciting and terrifying. It paints a picture of joy for some—and deep sorrow for others. To the faithful believer, it provides powerful assurance that they have a place reserved at the wedding banquet prepared for the Bride of Christ and Jesus, the Bridegroom. It is the fulfillment of a long-anticipated promise, a celebration of their relationship—intimate, sacred, and eternal. </p>
						<p class="text-black-50 mb-0">This banquet will be a time of unimaginable rejoicing, where the Bride will finally see Jesus face-to-face, not through faith, but with her own eyes. She will dine and fellowship with the One who gave everything for her, clothed not in her own righteousness but in the radiance He provided. There will be no more pain, no more striving—only joy, worship, and love unfiltered by this broken world. And this celebration won’t be brief or symbolic—it will last seven years in heavenly splendor while judgment unfolds below. While the Earth groans in chaos, the Bride will be safe in the arms of her Bridegroom, honored, cherished, and made ready for the final unveiling.</p>
						
                    `,
                    image: "assets/img/page12.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">In this parable, all ten virgins represent people who outwardly identify as followers of Christ. They all had lamps, they were all waiting for the bridegroom, and they all appeared to be part of the wedding celebration. But only five were truly prepared. The five wise virgins carried full jars of oil—symbolizing the indwelling fullness of the Holy Spirit and a life genuinely surrendered to God. These believers weren’t just Christian in name or appearance—they lived in daily dependence on the Spirit, cultivating intimacy with the Lord. They actively pursued the things of God, growing in faith, and walking in joyful obedience, even in the unseen moments. Their oil was not borrowed or faked—it was real, and it was theirs.</p>
						<p class="text-black-50 mb-0">The five wise virgins didn’t just believe in Jesus—they longed for Him. They loved the Lord and eagerly anticipated their union with Him, living each day with eternity in mind. Their lives were marked by devotion, not just emotion, and by faithfulness in both the seen and unseen moments. They loved the things God loves (see Psalm 119:97) and hated what God hates (see Proverbs 8:13, 1 John 2:16). They weren’t perfect, but they were prepared.</p>
						<p class="text-black-50 mb-0">They desired to keep the commandments of God:</p>
						<p class="text-black-50 mb-0">“This is the love of God, that we obey His commands—which are not burdensome.” (1 John 5:3)</p>
						<p class="text-black-50 mb-0">They desired to pray, read His Word, and worship the Lord:</p>
						<p class="text-black-50 mb-0">“Oh God, You are my God. Earnestly, I seek You; my soul thirsts for You in a dry and weary land without water. I have seen You in the sanctuary and beheld Your power and glory. Because Your love is better than life, my lips will glorify You. I will praise You as long as I live, and in Your name, I will lift up my hands. My soul is satisfied as with the richest of foods; with singing lips, my mouth will praise You.” (Psalm 63:1-5)</p>
						<p class="text-black-50 mb-0">Finally, they longed for the return of their Savior:</p>
						<p class="text-black-50 mb-0">“Now there is in store for me the crown of righteousness, which the Lord, the righteous Judge, will award to me on that day—and not only to me but also to all who have longed for His appearing (2 Timothy 4:8)</p>
						<p class="text-black-50 mb-0">On the other hand, the five foolish virgins may have looked the part, carrying lamps like everyone else, but their hearts were far from God. Perhaps they once recited a prayer without understanding, had a fleeting emotional experience, or attended church out of routine. But over time, the pull of the world grew stronger. Comfort, distraction, and the pursuit of selfish gain slowly replaced their hunger for God. The oil that once could have been theirs was never gathered. They put off true surrender, assuming they had more time.</p>
						

                    `,
                    image: "assets/img/page13.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">We’re reminded of the rich fool who said to himself:</p>
						<p class="text-black-50 mb-0">“‘You have plenty of good things laid up for many years. Take life easy; eat, drink, and be merry.’ But God said to him, ‘You fool! This very night, your life will be demanded of you. Then who will get what you have prepared for yourself?’ This is how it will be with anyone who stores up things for himself but is not rich toward God.” (Luke 12:19-21)</p>
						<p class="text-black-50 mb-0">Many come to Christ believing they’ve acquired spiritual “fire insurance.” They may claim His name but live as if He’s distant or optional—giving Him their Sundays but not their hearts. They go through the motions without true surrender, mistaking routine for relationship. But Jesus desires a Bride who loves Him with all her heart, soul, mind, and strength. To the lukewarm church in Laodicea, Jesus gave this warning:</p>
						<p class="text-black-50 mb-0">“I know your deeds, that you are neither hot or cold. I wish you were either one or the other! So, because you are lukewarm—neither hot or cold—I am about to spit you out of my mouth. You say, ‘I am rich; I have acquired wealth and do not need a thing.’ But you do not realize that you are wretched, pitiful, poor, blind, and naked.” (Revelation 3:16-17)</p>
						<p class="text-black-50 mb-0">It is, therefore, crucial that we consistently examine our faith to ensure we remain in true communion with our Savior:</p>
						<p class="text-black-50 mb-0">“Work out your faith with fear and trembling.” (Philippians 2:12)</p>
						<p class="text-black-50 mb-0">The Lord paid the highest price for our salvation; we must not treat it lightly. When Jesus returns for His people, He seeks a pure and holy Church longing for His presence—not a half-hearted bride ashamed of Him or seeking worldly pleasures over purity. He’s not coming back for a distracted Church but for one dressed in readiness, with lamps full and hearts burning for Him. This is not a time to play games with grace or assume we have more time. The call is urgent. The Groom is near. Let us be found watching, waiting, and wholly surrendered when He comes. Those who truly love Him will not be caught off guard—they will be the ones wide awake in the midnight hour.</p>
						<p class="text-black-50 mb-0">As confusion, deception, and global unrest continue to rise, it’s worth remembering that even Jesus’ disciples were desperate to understand the signs of the end—what to watch for and when He would return in power and glory. They weren’t looking for vague comfort—they wanted real answers, and Jesus didn’t leave them in the dark:</p>
						

                    `,
                    image: "assets/img/page14.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">“Tell us, when will these things happen, and what will be the sign of your coming and the end of the age?” Jesus answered, “See to it that no one leads you astray. For many will come in my name, saying, ‘I am the Christ,’ and they will lead many astray. And you will hear of wars and rumors of wars… Nation will rise against nation, and kingdom against kingdom, and there will be famines and Earthquakes in various places. All these are the beginning of the birth pains.” (Matthew 24:3-8)</p>
						<p class="text-black-50 mb-0">Birth pains intensify and increase in frequency as the time of birth approaches. This is precisely what’s happening today. Ominous signs on the Earth and in the heavens are multiplying at an alarming rate. Strange weather patterns, flocks of birds mysteriously dropping dead, enormous schools of fish washing ashore worldwide—the foreboding headlines seem endless (see Zephaniah 1:3). Massive Earthquakes, like those in Japan, alter the very rotation of the planet (see Isaiah 24:20). Asteroids frequently pass dangerously close to Earth, bodies of water turn blood red, enormous swarms of locusts ravage the Middle East, and people worldwide rage over political and cultural divisions. The New World Order’s “Great Reset” is already underway, and out of this chaos, they will usher in their counterfeit “Messiah.”</p>
						<p class="text-black-50 mb-0">So, you might ask, what exactly are we being rescued from? The answer is sobering. The Book of Revelation lays out in graphic detail the horrors awaiting those left behind after the Rapture. Once the Church is caught up—removed from the Earth at the close of Revelation 3—the scene shifts dramatically. Chapters 4 and 5 provide a glimpse into the throne room of Heaven, revealing that every event on Earth during the Tribulation is first decreed in the heavenly realm. The judgments that follow are not random—they are precise acts of divine justice.</p>
						<p class="text-black-50 mb-0">What unfolds next is a devastating cascade of judgment: the breaking of the seven seals unleashes conquest, war, famine, and death. As the seventh seal is opened, it gives way to seven trumpets—each one sounding a new wave of catastrophe, from environmental devastation to demonic torment. </p>
						<p class="text-black-50 mb-0">Finally, the seven bowls of God’s wrath are poured out without mixture, bringing about the complete collapse of Earthly systems and the final reckoning of rebellious humanity. Each stage grows more intense, more global, and more undeniable, as the wrath of God is poured out in full upon a world that rejected His mercy.</p>
						<p class="text-black-50 mb-0">This is what the Rapture spares the faithful from—not mere hardship, but the most terrifying era of divine judgment the world has ever seen. And the signs suggest it could begin at any moment.</p>
                    `,
                    image: "assets/img/page15.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>What Happens During the Tribulation?</h4>
						<p class="text-black-50 mb-0">As the seals begin to open, we are introduced to the Antichrist, who comes promising peace but ultimately brings worldwide war. The second seal ushers in widespread warfare; the third seal leads to economic chaos; the fourth brings further death by sword, famine, and plague. The fifth seal suggests mass martyrdom of the saints—those who put their faith in Christ after the Rapture. The sixth seal triggers a global Earthquake, and the sun turns dark while the moon becomes like blood. </p>
						<p class="text-black-50 mb-0">Finally, the seventh seal introduces the seven trumpets. This is when things become truly devastating. Fire falls from the heavens. Waters turn bitter. Darkness spreads. The Earth trembles under judgment, and humanity is gripped by terror. Each trumpet blast serves as both a warning and a consequence, yet even in the midst of chaos, many still refuse to repent. The long-withheld wrath of God is unleashed on an unrepentant world.</p>
						<p class="text-black-50 mb-0">The first trumpet unleashes hail and fire mixed with blood, burning up a third of the Earth, likely caused by a giant meteor strike. The second trumpet reveals something like a huge mountain ablaze, thrown into the sea, destroying a third of the oceans and marine life (see Revelation 8:6). Trumpet three delivers a meteor named Wormwood, poisoning fresh waters. At the fourth trumpet, the Archangel Michael strikes, and a third of the heavens turn dark. At the fifth trumpet, demonic locusts are released from the abyss. These creatures are led by “Apollyon,” derived from Apollo. They torment humanity with scorpion-like stings lasting five months. The sixth trumpet releases four mighty angels who kill a third of mankind through fire, smoke, and sulfur (see Revelation 9:13-19).</p>
						<p class="text-black-50 mb-0">Finally, the seventh trumpet announces God’s supreme reign upon His throne, even amidst the world’s chaos.</p>
						<p class="text-black-50 mb-0">“I saw another great and marvelous sign in heaven: seven angels with the seven last plagues—last because with them God’s wrath is completed.” (Revelation 15:1)</p>
                    `,
                    image: "assets/img/page16.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">The first bowl of wrath inflicts painful sores upon those who accepted the Mark of the Beast. The second bowl turns the seas into blood, killing all sea life. The third bowl transforms all fresh water into blood. The fourth causes the sun to scorch multitudes. The fifth plunges the kingdom of the Beast into deep darkness. The sixth dries up the Euphrates, enabling the kings from the East to gather against Israel at Armageddon. With the seventh bowl, a loud voice from God’s throne declares, “It is done!” A catastrophic Earthquake shakes the globe.</p>
						<p class="text-black-50 mb-0">While these judgments devastate humanity, other frightening events unfold with relentless cadence. As the Antichrist consolidates his power, only those marked by the Beast may buy or sell. Everyone else? Shut out of the system (see Revelation 13). Tragically, everyone who willingly receives this mark seals their eternal fate, damned to hell forever.</p>
						<p class="text-black-50 mb-0">Two witnesses will preach boldly against the Antichrist, supernaturally protected by God. However, halfway through the tribulation, they are killed, and after three-and-a-half days, they miraculously rise from the dead and ascend to heaven (Revelation 11). Near the tribulation’s end, Babylon—the great commercial hub of the world—is destroyed (Revelation 18).</p>
						<p class="text-black-50 mb-0">Finally, the world’s armies gather against Christ at the Battle of Armageddon, where they are utterly destroyed (Revelation 19:11-21). Jesus casts the Beast and the False Prophet into the lake of burning sulfur. Satan—the ancient serpent or the dragon—is bound and thrown into the Abyss for a thousand years.</p>
						<p class="text-black-50 mb-0">Today, the Antichrist is fully prepared to step onto the world stage. Discussions of peace treaties are significant because the tribulation officially begins when a seven-year peace treaty is confirmed (Daniel 9:27). Talks about rebuilding the Jewish Third Temple are also underway, fulfilling necessary prophecy.</p>
						<p class="text-black-50 mb-0">The groundwork for a one-world digital currency is already being established. Advances in technology—such as microchips implanted in the hand or forehead—enable unprecedented identification and tracking. Meanwhile, the prophetic alliance of Russia, Syria, and Iran foretold in Ezekiel 38-39 is firmly in place. Could the world be any closer to the brink of apocalypse?</p>
                    `,
                    image: "assets/img/page17.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>Time for Some Good News!</h4>
						<p class="text-black-50 mb-0">The picture of doom painted here does not have to be your future. God is merciful and fervently desires that none should perish:</p>
						<p class="text-black-50 mb-0">“The Lord is not slow to fulfill His promise…but is patient toward you, not wishing that any should perish, but that all should reach repentance.” (2 Peter 3:9)</p>
						<p class="text-black-50 mb-0">In Christ, God made a way for broken people to be restored, adopted, and brought near as His own beloved children. Knowing we would sin and be separated from Him, He had a redemptive plan even before time began. He sent His Son, Jesus Christ, to pay the ultimate price for our sins so we might dwell eternally with Him. This was not a backup plan—it was the expression of His love from the very beginning.</p>
						<p class="text-black-50 mb-0">Consider what’s commonly called the Romans Road to salvation:
						<ol>
							<li>“For all have sinned and fallen short of the glory of God.” (Romans 3:23)</li>
							<li>“But God demonstrates His love for us in this: While we were still sinners, Christ died for us.” (Romans 5:8)</li>
							<li>“For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.” (Romans 6:23)</li>
							<li>“If you confess with your mouth, ‘Jesus is Lord,’ and believe in your heart that God raised Him from the dead, you will be saved… Anyone who trusts in Him will never be put to shame.” (Romans 10:9-11)</li>
							<li>“The Spirit Himself bears witness with our spirit that we are children of God.” (Romans 8:16)</li>
						</ol>
						<p class="text-black-50 mb-0">God’s message of grace demonstrates His immense love for us, as He desires to spend eternity with us. He created us to glorify and enjoy Him forever, yet our sin separated us from His presence. Christ offered the perfect sacrifice, paying a debt He didn’t owe—one we could never pay.</p>
						<p class="text-black-50 mb-0">If we receive this incredible gift and believe in the Son of God, Scripture says we are saved:</p>
						<p class="text-black-50 mb-0">“To all who received Him, to those who believed in His name, He gave the right to become children of God—children born not of natural descent, nor of human decision, nor a husband’s will, but born of God.” (John 1:12-13)</p>
                    `,
                    image: "assets/img/page18.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">Even with such a costly gift offered freely, not everyone will receive it. The invitation is open to all, but the path is not popular—and Scripture makes that painfully clear. Sadly, many reject this gift, bringing destruction upon themselves:</p>
						<p class="text-black-50 mb-0">“Enter through the narrow gate. Wide is the gate, and broad is the road that leads to destruction, and many enter through it. But small is the gate, and narrow is the road that leads to life, and only a few find it.” (Matthew 7:13-14)</p>
						<p class="text-black-50 mb-0">“There is no other name under heaven given to men by which we must be saved.” (Acts 4:12)</p>
						<p class="text-black-50 mb-0">“Jesus answered, ‘I am the way, the truth, and the life. No one comes to the Father except through Me.’” (John 14:6)</p>
						<p class="text-black-50 mb-0">He did everything necessary by dying for you. Won’t you make the right choice today? Time is rapidly running out. Today is the day of salvation—not tomorrow, not someday. Apart from Christ, your future holds nothing worthwhile, for the world and its evil desires are passing away. Anything good, anything that you truly love, it all came from him anyway, and our Savior delights to share His good gifts with those who earnestly love Him.</p>
						<p class="text-black-50 mb-0">The birth pains are accelerating, becoming more and more intense with each passing day. The signs shout, will you refuse to listen? It is dangerous to delay, hoping to slip into heaven at the last minute. This is the last minute. And choosing not to decide is still a decision.</p>
						<p class="text-black-50 mb-0">Answer the call of your Savior:</p>
						<p class="text-black-50 mb-0">“Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in and dine with him, and he with Me.” (Revelation 3:20)</p>
                    `,
                    image: "assets/img/page19.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">He is knocking at your door to save you, not to condemn you. He sees the weight you carry, the pain you hide, and the questions you’re afraid to ask. He’s not looking for perfection; He’s looking for surrender. The door only opens from the inside, and He will not force His way in. Don’t let the noise of this life drown out the most important invitation you will ever receive. The time to come home is now. </p>
						<p class="text-black-50 mb-0">Whatever you’ve done, however far away you feel—you are not beyond His reach. Jesus died with your name on His heart and rose to offer you eternal life, not just survival. Every breath you’ve been given is a chance to say yes. Hell is real, but so is grace. And it’s reaching for you even now.</p>
						<p class="text-black-50 mb-0">But even now—before the final trumpet sounds, before the wrath of God is poured out in full—you still have time. The door of mercy is still open. Jesus has not returned yet, and that delay is not indifference—it’s grace. The same God who judges sin is the God who sent His Son to bear that judgment in your place. You don’t have to be left behind. You don’t have to face what’s coming. The cross of Christ is the ark of this generation, and the invitation to enter it is extended to you right now. Not because you’re strong. Not because you’re good. But because He is. All of history is racing toward a final moment—but today is still called today. You’re not too late.</p>
						<p class="text-black-50 mb-0">And maybe you’re thinking, “I’ve tried before. I always fail. I mess everything up. I’m too weak. Too broken. Too far gone.” But listen: God doesn’t ask you to be strong. He asks you to be honest. You don’t need to clean yourself up first—He already knows your mess. What He wants is your heart, your surrender, your yes.</p>
						<p class="text-black-50 mb-0">Jesus didn’t come for the proud or the perfect—He came for sinners. For the foolish, the weak, the rejected. For the ones who’ve messed it up again and again, even when they knew better. Grace isn’t for the worthy—it’s for the desperate. For the tired, the ashamed, the ones who’ve already given up on themselves. And if that’s you, then you are exactly the one He came to rescue. Don’t let the fear of failing again keep you from the One who already took your punishment and rose again to give you life. He came specifically for you, not just for everyone else—He came FOR YOU. Today is the day, open the door and let Him in.</p>
                    `,
                    image: "assets/img/page20.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>Come to Jesus and Receive New Life</h4>
						<p class="text-black-50 mb-0">If you recognize your need for God’s mercy and long to spend eternity with Him, offer this prayer with a heart of faith, trusting in the strength and grace He freely gives:</p>
						<p class="text-black-50 mb-0">Dear God in Heaven,
						<br/>I am a sinner, separated from You because of my sin. Have mercy on me, for I believe Your love is better than life. I believe You died for all my sins—past, present, and future. Because You love me with an eternal love, I ask You to forgive all my sins. I desire to turn away from sin and fall into Your loving arms. Please accept me into Heaven and make me worthy through the blood of Your Son, Jesus Christ, my Savior. Because You first loved me, I love You. I receive Your love right now. Fill me with Your Holy Spirit so I may have the wisdom and courage to face the rest of my life. Through this small amount of faith, I believe You have given me the right to become a child of God. Thank You, Father. I will follow You as Your dear child, now and forever!</p>
						<p class="text-black-50 mb-0">If you prayed sincerely to receive Jesus as your Savior, the Bible confidently declares you are now a new creation—no longer bound in sin, no longer separated from God.</p>
						<p class="text-black-50 mb-0">Coming to Christ isn’t the end of the journey—it’s the beginning of a new life:</p>
						<p class="text-black-50 mb-0">“If anyone is in Christ, the new creation has come: the old has gone, the new is here!” (2 Corinthians 5:17)</p>
						<p class="text-black-50 mb-0">When we accept His gift of salvation, we aren’t just forgiven; we are made new from the inside out. Our identity shifts, our purpose deepens, and the Spirit of God begins a transforming work in us. We’re no longer defined by our past, our pain, or our failures—we are now citizens of Heaven, children of the Most High. But with this new life comes a call to live differently, to grow, and to let go of the things that once held us captive.</p>
                    `,
                    image: "assets/img/page21.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">In the strength of His Holy Spirit, we are boldly encouraged to:</p>
						<p class="text-black-50 mb-0">“Put off your old self, which is being corrupted by evil desires; to be made new in the attitude of your minds; and to put on the new self, created to be like God in true righteousness and holiness.” (Ephesians 4:22-24)</p>
						<p class="text-black-50 mb-0">Get a reliable Bible, one you can read and understand easily—whether that’s a study Bible, a simpler translation, or one with devotionals to help guide your journey. Don’t just let it sit on the shelf; open it daily, even if only for a few minutes. Let God’s Word become your foundation, your anchor, and your compass. It will teach you the truth, strengthen your spirit, and remind you exactly who you are in Christ when the world tries to make you forget.</p>
						<p class="text-black-50 mb-0">Find fellowship with a healthy group of believers who love Jesus and are serious about living for Him. You weren’t meant to walk this journey alone. There is power in community, encouragement in shared faith, and healing in honest relationships. Look for a church that teaches the Word faithfully, loves well, and calls you higher. You’ll need people who will pray with you, challenge you, laugh with you, and help you grow when the road gets tough. Brothers and sisters who will become like a new family and support you on this journey. </p>
						<p class="text-black-50 mb-0">Above all, seek the Lord with all your heart—not just in the good moments but in the struggles, doubts, and everyday decisions. He is not far off; He is near, and He delights in walking with those who call on His name. The truths and promises in Scripture apply to all His children—including you. Don’t let shame or insecurity lie to you about your worth. God has a purpose and a plan for your life that no one else can fulfill—a calling that not even the devil himself can take away (see Romans 8:28-39).</p>
						<p class="text-black-50 mb-0">The Lord longs to dwell with you—not just to save you, but to know you deeply, walk beside you daily and transform your life from the inside out. He’s not waiting for perfection; He meets you exactly where you are and calls you His beloved. Let Him lead. Let Him heal. Let Him show you what real love is—a love that never fades, never fails, and never lets go. Rejoice with exceeding joy: you’ve made the best decision of your life, and all of Heaven rejoices with you.</p>
						<p class="text-black-50 mb-0">I look forward to meeting you in eternity—welcome to the family.</p>
                    `,
                    image: "assets/img/page22.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>Behold Your New Future in Christ</h4>
						<p class="text-black-50 mb-0">“I consider that our present sufferings are not worth comparing with the glory that will be revealed in us. For the creation waits in eager expectation for the children of God to be revealed.” (Romans 8:18-19)</p>
						<p class="text-black-50 mb-0">“He will also keep you firm to the end so that you will be blameless on the day of our Lord Jesus Christ.” (1 Corinthians 1:8)</p>
						<p class="text-black-50 mb-0">“Our citizenship is in heaven. And we eagerly await a Savior from there, the Lord Jesus Christ, who will transform our lowly bodies to be like His glorious body by the power that enables Him to bring everything under His control.” (Philippians 3:20-21)</p>
						<p class="text-black-50 mb-0">“When Christ, who is your life, appears, then you also will appear with Him in glory.” (Colossians 3:4)</p>
						<p class="text-black-50 mb-0">“Wait for His Son from heaven, whom He raised from the dead—Jesus, who rescues us from the coming wrath.” (1 Thessalonians 1:10)</p>
						<p class="text-black-50 mb-0">“May God Himself, the God of peace, sanctify you through and through. May your whole spirit, soul, and body be kept blameless at the coming of our Lord Jesus Christ.” (1 Thessalonians 5:23)</p>
						<p class="text-black-50 mb-0">“I charge you to keep this command without spot or blame until the appearing of our Lord Jesus Christ.” (1 Timothy 6:14)</p>
						<p class="text-black-50 mb-0">“In the presence of God and of Jesus Christ, who will judge the living and the dead, and given His appearing and His kingdom, I give you this charge: Preach the word; be prepared in season and out of season.” (2 Timothy 4:1-2)</p>
                    `,
                    image: "assets/img/page23.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">“For the grace of God has appeared that offers salvation to all people. It teaches us to say ‘No’ to ungodliness and worldly passions, and to live self-controlled, upright, and godly lives in this present age while we wait for the blessed hope—the appearing of the glory of our great God and Savior, Jesus Christ.” (Titus 2:11-13)</p>
						<p class="text-black-50 mb-0">“Christ was sacrificed once to take away the sins of many, and He will appear a second time, not to bear sin, but to bring salvation to those waiting for Him.” (Hebrews 9:28)</p>
						<p class="text-black-50 mb-0">“You, too, be patient and stand firm, because the Lord’s coming is near.” (James 5:8)</p>
						<p class="text-black-50 mb-0">“Therefore, with alert and fully sober minds, set your hope on the grace to be brought to you when Jesus Christ is revealed at His coming.” (1 Peter 1:13)</p>
						<p class="text-black-50 mb-0">“Dear friends, now we are children of God, and what we will be has not yet been made known. But we know that when Christ appears, we shall be like Him, for we shall see Him as He is.” (1 John 3:2)</p>
						<p class="text-black-50 mb-0">“Keep yourselves in God’s love as you wait for the mercy of our Lord Jesus Christ to bring you to eternal life.” (Jude 21)</p>
						<p class="text-black-50 mb-0">“Jesus told them, ‘Truly I tell you, at the renewal of all things when the Son of Man sits on His glorious throne, you who have followed Me will also sit on twelve thrones… And everyone who has left houses or brothers or sisters or father or mother or wife or children or fields for My sake will receive a hundred times as much and will inherit eternal life.’” (Matthew 19:28-29)</p>

                    `,
                    image: "assets/img/page24.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>Until That Glorious Day Comes</h4>
						<p class="text-black-50 mb-0">The Scriptures we have explored reveal the glorious hope and promise believers have in Jesus Christ. Despite the suffering and challenges we may face now, the future glory awaiting us far outweighs it all. We look forward to the day when His power transforms and makes us blameless. The return of our Lord Jesus Christ is imminent, and we eagerly anticipate His coming, knowing it will bring salvation and deliverance from the wrath to come.</p>
						<p class="text-black-50 mb-0">As we navigate this present age, let us hold fast to God’s Word by living self-disciplined, righteous, and godly lives. We are called to proclaim the Gospel and remain firm in our faith until Christ returns. Our hope is anchored in God’s grace, which offers salvation to all people and teaches us to reject ungodliness and seek righteousness.</p>
						<p class="text-black-50 mb-0">May we continually set our minds on Christ’s coming, placing our hope in the abundant grace and eternal life revealed in Him. We are children of God, and although our future glory has not yet been fully revealed, we anticipate the day when we will become like Him and behold Him in all His glory.</p>
						<p class="text-black-50 mb-0">While we await the mercy of our Lord Jesus Christ, let us remain steadfast in God’s love, confident that He will faithfully preserve us until He brings us into eternal life. The promises and truths in Scripture offer every believer comfort, security, and hope.</p>
						<p class="text-black-50 mb-0">In light of these truths, let us live in constant preparation, fulfilling God’s purposes for our lives. We look forward to dwelling with Him throughout all eternity. May the grace and peace of our Lord Jesus Christ be with you as we press forward together, eagerly awaiting the fulfillment of all His promises.</p>
                    `,
                    image: "assets/img/page25.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<h4>Joy Unrelenting in Prayer and Praise</h4>
						<p class="text-black-50 mb-0">We encourage you to pray in your own words. God isn’t waiting for polished lines—He’s waiting for you. Whether you speak with trembling hands or loud praise, whether you come carrying joy or dragging despair, He welcomes it all. Every confession, every question, every tangled thought. He already sees what you’re hiding—from the world, from the people around you, even from yourself. And yet, He never turns away.</p>
						<p class="text-black-50 mb-0">This is exactly why entering God’s presence can feel terrifying—because He sees it all. No masks. No filters. No pretending. His light shines into the dark corners we’d rather leave untouched. But here’s the miracle: there is no condemnation in that light. The sting of death is gone. The curse has been broken. Christ has carried the judgment and left you only with grace. You don’t have to impress Him.</p>
						<p class="text-black-50 mb-0">One of the most powerful and enduring prayers in Christian history is the one Jesus Himself gave to His disciples. Known as the Lord’s Prayer, it offers a simple yet profound model for how we can speak to our Heavenly Father—with reverence, honesty, dependence, and trust.</p>
						<p class="text-black-50 mb-0">This wasn’t just a set of words to memorize but a framework for real, personal communion with God. Here, Jesus teaches us to begin with worship, align our will with His, trust Him for our daily needs, seek forgiveness with humility, and ask for His protection and guidance in a broken world. It reminds us that we are not alone, that God is holy yet near, sovereign yet intimately involved in our everyday lives.</p>
						<p class="text-black-50 mb-0">The Lord’s Prayer isn’t just for quiet moments in church pews—it’s for your bedroom, your car, and your most anxious hours. Whether whispered through tears or spoken in peace, these words have been prayed by believers across centuries and continents. When you don’t know what to say, when the pain is too heavy or silence too loud, this prayer gives voice to your spirit, drawing you back to your Father:</p>
                    `,
                    image: "assets/img/page26.jpg" // Replace with your actual image path
                },
                {
                    text: ` 
						<p class="text-black-50 mb-0">The Lord’s Prayer<br/>
						Our Father, who art in heaven,<br/>
						Hallowed be Thy name.<br/>
						Thy kingdom come,<br/>
						Thy will be done,<br/>
						On Earth as it is in heaven.<br/>
						Give us this day our daily bread,<br/>
						And forgive us our trespasses,<br/>
						As we forgive those who trespass against us.<br/>
						And lead us not into temptation,<br/>
						But deliver us from evil.<br/>
						For Thine is the kingdom,<br/>
						And the power, and the glory,<br/>
						Forever and ever. Amen.</p>
						<p class="text-black-50 mb-0">God has chosen and loved you, not based on your perfection but on His unshakable grace. Remembering that new reality—even when we wander—is often the hardest and most important fight of faith. The enemy will try to shame you, accuse you, and drag you back into fear. Don’t let him. Stand firm in the truth that you belong to Christ.</p>
                    `,
                    image: "assets/img/page27.jpg" // Replace with your actual image path
                }
            ];